//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsImg
    {
        public string GoodsId { get; set; }
        public string Small1 { get; set; }
        public string Big1 { get; set; }
        public string Small2 { get; set; }
        public string Big2 { get; set; }
    }
}
